#!/bin/bash
############################################################
# Set up logging

exec >$HOME/.xinit-errors 2>&1
echo "===== .xinitrc startup: $(date +'%Y-%m-%d %H:%M:%S')"


############################################################
# Environment and device configuration

# `/usr/bin/xdg-{settings,open}` understands only a few popular
# desktop environments (see the `detectDE()` function). We set this so
# that we can actually set preferences for xdg-open (which is used by,
# e.g., Slack) rather than just live with the default browser list
# that puts Firefox before Chrome.
#
export XDG_CURRENT_DESKTOP=XFCE

. $HOME/.local/bin/xresetup || echo 1>&2 "ERROR: xresetup failed"


############################################################
# Start "background" programs

# Dbus appears to be started for us on login, though we should probably
# check for that and start it here if necessary.

xfce4-panel & sleep 1
ibus-daemon --xim --daemonize
xfce4-power-manager &
nm-applet &
blueman-applet &
xscreensaver -no-splash &

#   "Night light" for less blue light in evenings. We now use redshift
#   because it's maintained; fluxgui does not work on newer kernels. The
#   default GeoClue client may fail becuase it's not installed, location
#   services have been disabled in the GTK configuration, etc., so for
#   simplicity we just manually set the location to near Tokyo.
redshift-gtk -t 6500:3500 -l 35:139 &

#   Do not autostart dropbox sync if we don't have a sync'd copy.
if [[ -r ~/Dropbox/0-desc ]]; then
    #   If we don't have the dropbox.py control script kicking around
    #   (it comes with the Linux package), see if the headless version is
    #   available. Note that the latter, dropboxd, does not deamonize itself.
    dropbox start || { $HOME/.dropbox-dist/dropboxd & }
fi


############################################################
# Start "foreground" programs and window manager

xterm -name 'start' -geometry 80x59+730+0 &
exec fvwm
